In [1]:
#Import Libraries
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from KNeighbors import KNNClassifier

Data Preprocessing

In [2]:
#telecharger dataset
dataset = pd.read_csv("C:/Users/HP/Desktop/MLProject/Impl/Mobile Price Classification/data.csv")
dataset

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [3]:
#Vérification des valeurs manquantes
dataset.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [4]:
#Pour afficher les differents classe
classes = list(set(dataset['price_range'])) 
print('classes:',classes)

classes: [0, 1, 2, 3]


Splitting data into feature and labels && Lets standardize the data

In [5]:
#pour filter les attributs qui concernant Featuers seulement
X =  dataset.drop(["price_range"],axis=1)
#pour filter l'attribut qui concerne target => y
y = dataset["price_range"]

In [6]:
#afficher features => X
X

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2   2         20       756  2549     9     7   
1       0.7        136        3   6        905      1988  2631    17     3   
2       0.9        145        5   6       1263      1716  2603    11     2   
3       0.8        131        6   9       1216      1786  2769    16     8   
4       0.6        141        2  14       1208      1212  1411     8     2   
...     ...        ...      ...  ..        ...       ...   ...   ...   ...   
1995    0.8        106        6  14       1222      1890   668    13     4   
1996    0.2        187        4   3        915      1965  2032    11    10   
1997    0.7        108        8   3        868      1632  3057     9     1   
1998    0.1        145        5   5        336       670   869    18    10   
1999    0.9        168        6  16        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  
0            19        0             0     1  
1             7        1             1     0  
2             9        1             1     0  
3            11        1             0     0  
4            15        1             1     0  
...         ...      ...           ...   ...  
1995         19        1             1     0  
1996         16        1             1     1  
1997          5        1             1     0  
1998         19        1             1     1  
1999          2        1             1     1  

[2000 rows x 20 columns]

In [7]:
##afficher target => y
y

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,shuffle=True,random_state=0)

In [9]:
X_train = np.asarray(X_train)
X_test = np.asarray(X_test)

y_train = np.asarray(y_train)
y_test = np.asarray(y_test)

In [10]:
#pour desentraliser notre faetures
from sklearn.preprocessing import Normalizer
scaler = Normalizer()

normalized_X_train = scaler.transform(X_train)
normalized_X_test = scaler.transform(X_test)

In [11]:
print("X_train before normalize : ")
print(X_train[0:5])

print("X_train after normalize : ")
print(normalized_X_train[0:5])

X_train before normalize : 
[[1.232e+03 0.000e+00 2.900e+00 1.000e+00 1.000e+00 1.000e+00 2.400e+01
  3.000e-01 1.690e+02 5.000e+00 1.700e+01 3.610e+02 8.090e+02 1.257e+03
  1.600e+01 1.000e+01 1.600e+01 1.000e+00 0.000e+00 0.000e+00]
 [1.840e+03 0.000e+00 5.000e-01 1.000e+00 1.200e+01 0.000e+00 3.400e+01
  7.000e-01 1.420e+02 1.000e+00 1.600e+01 3.110e+02 1.545e+03 1.078e+03
  8.000e+00 0.000e+00 1.000e+01 0.000e+00 0.000e+00 0.000e+00]
 [1.692e+03 0.000e+00 2.100e+00 0.000e+00 4.000e+00 1.000e+00 2.000e+00
  9.000e-01 1.060e+02 1.000e+00 1.700e+01 1.899e+03 1.904e+03 3.779e+03
  9.000e+00 3.000e+00 7.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [5.080e+02 0.000e+00 8.000e-01 0.000e+00 7.000e+00 1.000e+00 4.200e+01
  3.000e-01 9.400e+01 1.000e+00 8.000e+00 3.900e+01 5.570e+02 6.630e+02
  1.300e+01 1.200e+01 7.000e+00 1.000e+00 0.000e+00 0.000e+00]
 [9.770e+02 1.000e+00 2.800e+00 1.000e+00 2.000e+00 0.000e+00 3.500e+01
  6.000e-01 1.650e+02 2.000e+00 1.500e+01 1.502e+03 1.862e+03 3.714e+03


In [ ]:
# Calculer la matrice de confusion
def matrixConffudion(y_test_new,y_pred_new):
    conf_matrix = confusion_matrix(y_test_new, y_pred_new)

# Extraire les valeurs de la matrice de confusion
    num_classes = conf_matrix.shape[0]
    tn, fp, fn, tp = [], [], [], []

    if num_classes == 2:
        tn, fp, fn, tp = conf_matrix.ravel()
    else:
        for i in range(num_classes):
            for j in range(num_classes):
                if i == j:
                    tp.append(conf_matrix[i, j])
                else:
                    fn.append(conf_matrix[i, j])
                    fp.append(conf_matrix[j, i])
        tn = sum(conf_matrix.flatten()) - (sum(tp) + sum(fp) + sum(fn))

# Afficher les valeurs
    print('Confusion matrix:\n', conf_matrix)
    print('True Negative (TN):', tn)
    print('False Positive (FP):', fp)
    print('False Negative (FN):', fn)
    print('True Positive (TP):', tp)

Load Model => KNN from scratch and sklearn

In [14]:
#KNN 
knn = KNNClassifier(k=4)
#pour entrener notre model from scratch avec normalized_X_train et y_train
knn.fit(normalized_X_train, y_train)
#pour faire la prediction
y_pred_scratch = knn.predict(normalized_X_test)
print(y_pred_scratch)  # Affiche [0, 1]


[3, 1, 3, 2, 1, 1, 0, 2, 2, 3, 1, 3, 0, 2, 1, 0, 3, 2, 2, 2, 2, 0, 2, 3, 1, 2, 2, 2, 3, 1, 2, 0, 2, 2, 3, 3, 0, 0, 3, 3, 2, 1, 3, 2, 2, 2, 0, 1, 2, 2, 0, 2, 1, 3, 0, 3, 3, 2, 0, 3, 3, 3, 3, 2, 1, 2, 3, 2, 3, 3, 2, 3, 1, 0, 1, 2, 3, 0, 2, 1, 3, 1, 2, 0, 0, 0, 2, 1, 2, 3, 2, 3, 1, 3, 0, 2, 2, 3, 0, 3, 2, 2, 2, 0, 3, 1, 3, 3, 2, 1, 1, 0, 0, 2, 2, 2, 3, 0, 0, 0, 0, 2, 1, 2, 1, 2, 1, 1, 1, 3, 1, 2, 2, 1, 3, 3, 3, 2, 0, 1, 2, 1, 2, 3, 0, 3, 0, 0, 3, 0, 0, 1, 1, 2, 3, 1, 0, 2, 0, 3, 2, 2, 2, 1, 2, 2, 3, 3, 1, 0, 3, 2, 3, 2, 3, 2, 2, 2, 3, 0, 2, 2, 3, 2, 2, 1, 1, 0, 2, 3, 1, 3, 0, 3, 3, 2, 1, 3, 3, 0, 3, 2, 3, 2, 1, 1, 3, 2, 1, 0, 0, 2, 2, 3, 0, 0, 1, 3, 1, 2, 3, 2, 0, 0, 2, 3, 2, 2, 2, 3, 1, 0, 0, 3, 1, 0, 2, 3, 0, 1, 0, 3, 3, 2, 0, 0, 2, 3, 2, 2, 3, 0, 3, 2, 3, 0, 2, 2, 2, 1, 0, 0, 1, 2, 3, 3, 1, 3, 3, 2, 0, 3, 1, 0, 2, 3, 3, 3, 1, 1, 0, 2, 1, 0, 0, 0, 3, 3, 2, 2, 0, 3, 2, 0, 0, 3, 2, 1, 1, 0, 0, 1, 3, 0, 1, 2, 3, 1, 2, 1, 2, 0, 3, 0, 2, 2, 3, 2, 1, 0, 1, 2, 1, 2, 0, 1, 0, 2, 3, 3, 3, 3, 0, 

Evaluation Model

In [15]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_scratch))

              precision    recall  f1-score   support

           0       0.81      0.78      0.80        95
           1       0.52      0.42      0.47        92
           2       0.39      0.47      0.43        99
           3       0.58      0.57      0.58       114

    accuracy                           0.56       400
   macro avg       0.57      0.56      0.57       400
weighted avg       0.57      0.56      0.57       400



Pour Tester mon model avec nouvelle data 

In [16]:
#842	0	2.2	0	1	0	7	0.6	188	2	2	20	756	2549	9	7	19	0	0	1
#1021	1	0.5	1	0	1	53	0.7	136	3	6	905	1988	2631	17	3	7	1	1	0
input_data = (1021,1,0.5,1,0,1,53,0.7,136,3,6,905,1988,2631,17,3,7,1,1,0)
#changing the input inot numpy array and reshaping
input_changed = np.array(input_data).reshape(1,-1)
#standardize the input
std_input = scaler.transform(input_changed)
k = 4
y_pred_scratch = knn.predict(std_input)
print(y_pred_scratch)

[2]


Avec Sklearn => Model

In [17]:
model = KNeighborsClassifier()

In [18]:
#Entrener notre model
model.fit(normalized_X_train,y_train)

KNeighborsClassifier()

In [19]:
#pour faire la prediction
traning_data_pred_sklearn = model.predict(normalized_X_test)
traning_data_pred_sklearn

array([3, 1, 2, 1, 1, 1, 0, 1, 2, 3, 1, 3, 0, 1, 1, 0, 3, 2, 3, 2, 1, 0,
       2, 3, 1, 2, 2, 1, 3, 1, 2, 0, 2, 1, 3, 3, 0, 0, 3, 3, 2, 1, 3, 1,
       2, 2, 0, 1, 3, 1, 0, 2, 1, 2, 1, 3, 3, 2, 0, 3, 3, 2, 3, 2, 1, 2,
       2, 2, 3, 3, 2, 3, 0, 0, 1, 2, 3, 0, 2, 1, 3, 1, 2, 0, 0, 0, 2, 0,
       2, 3, 1, 3, 1, 3, 0, 2, 1, 3, 0, 3, 2, 2, 2, 0, 3, 1, 2, 3, 2, 1,
       1, 0, 0, 2, 2, 2, 3, 0, 0, 0, 0, 2, 2, 2, 1, 2, 1, 1, 0, 3, 1, 3,
       1, 1, 3, 3, 3, 2, 0, 1, 2, 1, 2, 3, 0, 3, 0, 0, 3, 0, 0, 1, 1, 2,
       3, 1, 0, 3, 0, 2, 2, 2, 2, 1, 2, 3, 3, 3, 1, 0, 3, 2, 3, 2, 3, 2,
       2, 2, 3, 1, 2, 2, 3, 2, 3, 1, 2, 0, 2, 3, 1, 2, 1, 3, 3, 2, 0, 3,
       3, 0, 3, 2, 3, 1, 1, 2, 3, 3, 1, 0, 0, 2, 2, 3, 1, 0, 1, 3, 1, 3,
       3, 3, 0, 0, 2, 3, 3, 2, 1, 3, 1, 0, 0, 3, 1, 0, 2, 3, 0, 1, 0, 3,
       3, 1, 0, 0, 2, 2, 2, 1, 3, 0, 3, 1, 2, 0, 2, 2, 2, 1, 0, 0, 1, 2,
       3, 2, 1, 3, 2, 2, 0, 3, 1, 0, 1, 3, 3, 3, 3, 1, 0, 2, 2, 0, 0, 0,
       3, 3, 2, 2, 0, 3, 2, 0, 0, 3, 2, 1, 2, 0, 0,

Evaluer notre model avec sklearn

In [20]:
from sklearn.metrics import classification_report
print(classification_report(y_test,traning_data_pred_sklearn))

              precision    recall  f1-score   support

           0       0.77      0.73      0.75        95
           1       0.46      0.45      0.45        92
           2       0.41      0.47      0.44        99
           3       0.62      0.58      0.60       114

    accuracy                           0.56       400
   macro avg       0.56      0.56      0.56       400
weighted avg       0.57      0.56      0.56       400



In [21]:
#La matrix du confdusion
matrixConffudion(y_test,traning_data_pred_sklearn)

Confusion matrix:
 [[69 19  4  3]
 [17 41 26  8]
 [ 4 19 47 29]
 [ 0 11 37 66]]
True Negative (TN): -177
False Positive (FP): [17, 4, 0, 19, 19, 11, 4, 26, 37, 3, 8, 29]
False Negative (FN): [19, 4, 3, 17, 26, 8, 4, 19, 29, 0, 11, 37]
True Positive (TP): [69, 41, 47, 66]


In [22]:
#Pour tester notre model en utilisant sklearn  avec nouvelle data
input_data = (1021,1,0.5,1,0,1,53,0.7,136,3,6,905,1988,2631,17,3,7,1,1,0)
input_changed = np.array(input_data).reshape(1,-1)
std_input = scaler.transform(input_changed)
k = 4
y_pred_sklearn = model.predict(std_input)
print(y_pred_sklearn)

[2]


Sauvgarder notre model dans un fichier
=> utilise la bibliothèque joblib pour sauvegarder notre modèle KNN entraîné ainsi qu'un objet 
de mise à l'échelle standard (standard scalar) utilisé pour normaliser les données.
voici une explication du code

In [ ]:
#Tout d'abord, la bibliothèque joblib est importée.
import joblib

"""
enregistre le modèle KNN entraîné dans un fichier nommé "model.pkl", et que le modèle est
enregistré sous forme binaire dans le fichier.
"""
joblib.dump(model,'model.pkl')


""" 
enregistre l'objet de mise à l'échelle standard (standard scalar) dans un fichier
nommé "scalar.pkl". L'objet de mise à l'échelle standard est utilisé pour normaliser les données
d'entrée avant de les utiliser pour faire des prédictions avec le modèle. En le sauvegardant, 
on peut le charger ultérieurement et l'appliquer aux nouvelles données de la même manière que 
lors de l'entraînement.
"""
joblib.dump(scaler,'scalar.pkl')

"""
joblib.dump j'ai le utiliser pou sauvegarder le modèle et l'objet de mise à l'échelle standard
dans des fichiers distincts.
"""

""" 
Pour charger le modèle et l'objet de mise à l'échelle à partir des fichiers sauvegardés, 
on utilise les fonctions joblib.load('model.pkl') et joblib.load('scalar.pkl') respectivement.
"""